name: Buildctttt

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
       - uses: actions/checkout@v1
       - name: set up JDK 14.0.1
         uses: actions/setup-java@v1
         with:
          java-version: 11.0.7
       - name: Unit tests
         run: bash ./gradlew test --stacktrace
       - name: Unit tests results
         uses: actions/upload-artifact@v1
         with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html
        
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 15.0
        uses: actions/setup-java@v1
        with:
          java-version: 15.0
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
